# Generated by Django 5.1.5 on 2025-02-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_materialyz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='store_name',
            new_name='compnay_name',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='business_license',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='gst_number',
            field=models.CharField(blank=True, help_text='Optional: Upload a valid business license.', max_length=100, null=True),
        ),
    ]
